import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Link } from 'react-router-dom';
import { 
  Zap, 
  Battery, 
  Gauge, 
  Shield, 
  Wifi,
  Settings,
  ArrowRight,
  CheckCircle
} from 'lucide-react';
import inverterImage from '@/assets/solar-inverter.jpg';

const SolarInverters = () => {
  const features = [
    { icon: Gauge, title: 'High Efficiency', description: 'Up to 98% conversion efficiency rating' },
    { icon: Wifi, title: 'Smart Monitoring', description: 'Real-time performance tracking and alerts' },
    { icon: Shield, title: 'Protection Features', description: 'Over-voltage, under-voltage, and surge protection' },
    { icon: Settings, title: 'Easy Integration', description: 'Compatible with existing solar and battery systems' }
  ];

  const useCases = [
    'Residential solar power systems',
    'Commercial and industrial installations',
    'Off-grid and hybrid solutions',
    'Battery backup systems',
    'Grid-tie applications',
    'Microgrids and distributed energy'
  ];

  const specifications = [
    { label: 'Power Range', value: '1kW to 100kW' },
    { label: 'Efficiency', value: 'Up to 98.2%' },
    { label: 'Input Voltage', value: '150V to 850V DC' },
    { label: 'Output', value: '230V/400V AC' }
  ];

  return (
    <div className="min-h-screen pt-20">
      {/* Hero Section */}
      <section 
        className="relative py-32 bg-cover bg-center"
        style={{ backgroundImage: `linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url(${inverterImage})` }}
      >
        <div className="container mx-auto px-4">
          <div className="max-w-3xl text-white">
            <div className="flex items-center space-x-3 mb-6">
              <div className="flex items-center justify-center w-16 h-16 bg-gradient-nature rounded-full">
                <Zap className="h-8 w-8 text-primary-foreground" />
              </div>
              <h1 className="text-4xl md:text-5xl font-bold hero-text-shadow font-playfair">
                Solar Inverters
              </h1>
            </div>
            <p className="text-xl mb-8 hero-text-shadow leading-relaxed">
              Our inverters convert DC to AC efficiently and can be connected with existing solar 
              or battery systems, enabling uninterrupted, optimized energy use.
            </p>
            <Link to="/contact">
              <Button size="lg" className="btn-nature text-lg px-8 py-4 h-auto">
                Book a Free Consultation
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Details Section */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl md:text-4xl font-bold mb-8 text-center font-playfair">
              Advanced Solar Inverter Technology
            </h2>
            
            <div className="prose prose-lg max-w-none mb-12">
              <p className="text-lg text-muted-foreground leading-relaxed mb-6">
                Our solar inverters are the heart of any solar power system, converting the DC electricity 
                generated by solar panels into AC electricity that can be used by your home or business. 
                With advanced MPPT technology, our inverters maximize energy harvest from your solar array.
              </p>
              
              <p className="text-lg text-muted-foreground leading-relaxed mb-6">
                Featuring smart grid-tie capabilities, our inverters can seamlessly integrate with the utility 
                grid, allowing for net metering and optimal energy management. Built-in safety features protect 
                against electrical faults, while real-time monitoring helps track system performance.
              </p>
              
              <p className="text-lg text-muted-foreground leading-relaxed">
                Available in string, power optimizer, and micro-inverter configurations, we offer solutions 
                for every installation type. All units come with comprehensive warranties and professional 
                installation support to ensure optimal performance and longevity.
              </p>
            </div>

            {/* Specifications */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6 mb-16">
              {specifications.map((spec, index) => (
                <Card key={index} className="text-center hover:shadow-nature transition-all duration-300">
                  <CardContent className="p-6">
                    <h3 className="font-semibold text-primary mb-2">{spec.label}</h3>
                    <p className="text-muted-foreground">{spec.value}</p>
                  </CardContent>
                </Card>
              ))}
            </div>

            {/* Features Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-16">
              {features.map((feature, index) => {
                const IconComponent = feature.icon;
                return (
                  <Card key={index} className="hover:shadow-nature transition-all duration-300">
                    <CardContent className="p-6">
                      <div className="flex items-start space-x-4">
                        <div className="flex items-center justify-center w-12 h-12 bg-gradient-nature rounded-full flex-shrink-0">
                          <IconComponent className="h-6 w-6 text-primary-foreground" />
                        </div>
                        <div>
                          <h3 className="text-xl font-semibold mb-2 font-playfair">{feature.title}</h3>
                          <p className="text-muted-foreground">{feature.description}</p>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          </div>
        </div>
      </section>

      {/* Use Cases Section */}
      <section className="py-20 bg-muted/50">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl md:text-4xl font-bold mb-8 text-center font-playfair">
              Versatile Inverter Applications
            </h2>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {useCases.map((useCase, index) => (
                <div key={index} className="flex items-center space-x-3">
                  <CheckCircle className="h-6 w-6 text-primary flex-shrink-0" />
                  <span className="text-lg">{useCase}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-nature">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-primary-foreground mb-4 font-playfair">
            Maximize Your Solar Investment
          </h2>
          <p className="text-xl text-primary-foreground/90 mb-8 max-w-2xl mx-auto">
            Get the most efficient inverter solution for your solar system. 
            Our experts will recommend the perfect inverter for your specific requirements.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link to="/contact">
              <Button size="lg" variant="secondary" className="text-lg px-8 py-4 h-auto">
                Get Inverter Consultation
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
            </Link>
            <Link to="/projects">
              <Button size="lg" variant="outline" className="bg-transparent border-white text-white hover:bg-white hover:text-foreground text-lg px-8 py-4 h-auto">
                View System Examples
              </Button>
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
};

export default SolarInverters;